alter session set NLS_DATE_FORMAT = 'DD-MON-YYYY';
set term off
DROP TABLE CUSTOMER cascade constraints;
DROP TABLE MAGAZINE cascade constraints;
DROP TABLE MAGAZINESET cascade constraints;
DROP TABLE CUSTOMERSUB cascade constraints;

CREATE TABLE CUSTOMER(
CUSTOMERID				NUMBER(4),
CUSTOMERNAME			VARCHAR2(12),
CUSTOMERTITLE			VARCHAR2(13),
CUSTOMERADDRESS 		VARCHAR2(15),
CUSTOMERDOB 			DATE,
CONSTRAINT CUSTOMER_PK PRIMARY KEY (CUSTOMERID)); 

INSERT INTO CUSTOMER VALUES (1, 'Alpha', 'MR', '32 House Lane', '01-JAN-1990');
INSERT INTO CUSTOMER VALUES (2, 'Beta', 'MS', '32 House Lane', '01-FEB-1991');

CREATE TABLE MAGAZINE(
MAGAZINEID				NUMBER(4),
EDITIONID				NUMBER(4),
MAGTITLE				VARCHAR2(10),
MAGPUBLISHER			VARCHAR2(12),
RELEASEDATE				DATE,
CONSTRAINT MAGAZINE_PK PRIMARY KEY (MAGAZINEID));

INSERT INTO MAGAZINE VALUES (1, 10, 'MAG1', 'PUB1', '01-JAN-2000');
INSERT INTO MAGAZINE VALUES (2, 20, 'MAG2', 'PUB2', '02-JAN-2001');
INSERT INTO MAGAZINE VALUES (3, 30, 'MAG3', 'PUB3', '03-JAN-2003');

CREATE TABLE MAGAZINESET(
SETID					NUMBER(4),
MAG1ID					NUMBER(4),
MAG2ID					NUMBER(4),
MAG3ID					NUMBER(4),
CONSTRAINT MAGAZINESET_PK PRIMARY KEY (SETID),
CONSTRAINT MAG1ID_FK FOREIGN KEY (MAG1ID) REFERENCES MAGAZINE (MAGAZINEID),
CONSTRAINT MAG2ID_FK FOREIGN KEY (MAG2ID) REFERENCES MAGAZINE (MAGAZINEID),
CONSTRAINT MAG3ID_FK FOREIGN KEY (MAG3ID) REFERENCES MAGAZINE (MAGAZINEID));

INSERT INTO MAGAZINESET VALUES (1, 1, 2, 3);
INSERT INTO MAGAZINESET VALUES (2, 1, null, 3);

CREATE TABLE CUSTOMERSUB(
SUBID 					NUMBER(4),
CUSTOMERID 				NUMBER(4),
SETID					NUMBER(4),
SUBSTART				DATE,
SUBEND					DATE,
ACTIVE					NUMBER(1),
CONSTRAINT SUBID_PK PRIMARY KEY (SUBID),
CONSTRAINT CUSTOMERID_FK FOREIGN KEY(CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID),
CONSTRAINT SETID_FK FOREIGN KEY (SETID) REFERENCES MAGAZINESET(SETID));

INSERT INTO CUSTOMERSUB VALUES (1, 1, 1, '01-JAN-2000', '02-JAN-2001', 0);
INSERT INTO CUSTOMERSUB VALUES (2, 2, 2, '02-JAN-2001', '03-JAN-2002', 1);
set term on